// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8OimNdIw7c_MzF9v62T4uk0gxsP_MGg',
    appId: '1:1093327579845:web:faae89461f8b9844709eac',
    messagingSenderId: '1093327579845',
    projectId: 'kreavana-com',
    authDomain: 'kreavana-com.firebaseapp.com',
    storageBucket: 'kreavana-com.firebasestorage.app',
    measurementId: 'G-YP3CTTHZHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQG5mIC1PGElMqYmsHEcItI3iExbbq42A',
    appId: '1:1093327579845:android:f1d7be7d7974a1aa709eac',
    messagingSenderId: '1093327579845',
    projectId: 'kreavana-com',
    storageBucket: 'kreavana-com.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVoM6TLZ1Qp5HXRPnsiakQQWkhFUITQY',
    appId: '1:1093327579845:ios:20d5f0e1cccf970f709eac',
    messagingSenderId: '1093327579845',
    projectId: 'kreavana-com',
    storageBucket: 'kreavana-com.firebasestorage.app',
    iosClientId:
        '1093327579845-3coe8jgs9k99vcfvrf20oij24jsuc9bq.apps.googleusercontent.com',
    iosBundleId: 'cv.alamkreasi.kreavana',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVoM6TLZ1Qp5HXRPnsiakQQWkhFUITQY',
    appId: '1:1093327579845:ios:20d5f0e1cccf970f709eac',
    messagingSenderId: '1093327579845',
    projectId: 'kreavana-com',
    storageBucket: 'kreavana-com.firebasestorage.app',
    iosClientId:
        '1093327579845-3coe8jgs9k99vcfvrf20oij24jsuc9bq.apps.googleusercontent.com',
    iosBundleId: 'cv.alamkreasi.kreavana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX8OimNdIw7c_MzF9v62T4uk0gxsP_MGg',
    appId: '1:1093327579845:web:d50c0089eb56d68d709eac',
    messagingSenderId: '1093327579845',
    projectId: 'kreavana-com',
    authDomain: 'kreavana-com.firebaseapp.com',
    storageBucket: 'kreavana-com.firebasestorage.app',
    measurementId: 'G-64TFLPM76W',
  );
}
